name: tracker_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  uuid: ^4.5.1
  go_router: ^16.2.4
  share_plus: ^12.0.0
  hooks_riverpod: ^3.0.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  introduction_screen: ^4.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  custom_lint: ^0.8.0
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
